### ISSUE TITLE
Nothing was iplemented

### ISSUE THREAD

**Issue by monacofj** [so-ii-2019/sh19-shellby#2]
?

**Comment by queirox-lucas** [comment]
The project uses the programs that already exists on Unix-like systems ( on /bin) and runs then. We used the exec in order to do so, interpreting  the input with the parser present in the libposixeg. Is it invalid? About the lack of redirections and pipes implementation, we did started to implement then, but we could not get rid of the bugs, so it was not indexed as a tag. BUT you can see that there is a branch in this repo that represents our attempts to implement then. I'm very confused with situation, maybe you are looking at the wrong branch, please take a look on the branch dev and the branch feature-builtins. We actually forgot to merge to master because we thought that the tag created was enough. Please, let us know if that was the problem.

**Comment by monacofj** [comment]
Ok, I checked the wrong branch.
Thanks. Closing issue,
